"""Skan natijasidan professional PDF hisobot yaratadi (fpdf2).

Eslatma: standart Helvetica shrifti latin-1 bilan cheklangan, shuning uchun
matnlar sodda lotin harflarida (o', g' kabi apostrof bilan) yoziladi va
emoji ishlatilmaydi. Bu hisobotni mijozga yuboriladigan toza hujjat qiladi.
"""
from __future__ import annotations

import os
import time
from typing import Any

from fpdf import FPDF

BRAND = "SentryScan Security Report"
ACCENT = (20, 90, 160)
GREY = (110, 110, 110)
OKC = (25, 135, 60)
WARN = (200, 120, 0)
BAD = (190, 40, 40)


def _latin(s: str) -> str:
    """latin-1 ga sig'maydigan belgilarni almashtiradi."""
    repl = {"’": "'", "‘": "'", "“": '"', "”": '"', "–": "-", "—": "-", "•": "-", "…": "..."}
    for a, b in repl.items():
        s = s.replace(a, b)
    return s.encode("latin-1", "replace").decode("latin-1")


class _PDF(FPDF):
    def header(self) -> None:
        self.set_fill_color(*ACCENT)
        self.rect(0, 0, self.w, 22, "F")
        self.set_xy(12, 6)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, BRAND)
        self.set_text_color(0, 0, 0)
        self.ln(20)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        self.cell(0, 8, f"Generated by SentryScan  |  Page {self.page_no()}", align="C")
        self.set_text_color(0, 0, 0)


def _h2(pdf: _PDF, text: str) -> None:
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 8, _latin(text), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.set_draw_color(*ACCENT)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(2)


def _kv(pdf: _PDF, key: str, val: str, color=None) -> None:
    key_w = 45
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(key_w, 6, _latin(key), new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "", 10)
    if color:
        pdf.set_text_color(*color)
    avail = pdf.w - pdf.r_margin - pdf.l_margin - key_w
    pdf.multi_cell(avail, 6, _latin(val), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)


def build_findings(r: dict[str, Any]) -> list[tuple[str, str]]:
    """(daraja, matn) ro'yxati. daraja: OK/LOW/MED/HIGH."""
    out: list[tuple[str, str]] = []
    d, s, h = r["dns"], r["ssl"], r["http"]

    if s.get("ok"):
        dl = s.get("days_left")
        if dl is not None and dl < 0:
            out.append(("HIGH", "SSL sertifikat muddati tugagan!"))
        elif dl is not None and dl < 21:
            out.append(("MED", f"SSL sertifikat muddati tez tugaydi ({dl} kun)."))
    else:
        out.append(("MED", "HTTPS/SSL ulanib bo'lmadi yoki sozlanmagan."))

    if h.get("ok"):
        for miss in h.get("missing", []):
            sev = "MED" if miss in ("HSTS", "CSP") else "LOW"
            out.append((sev, f"Xavfsizlik header'i yo'q: {miss}."))
        if not h.get("security_txt"):
            out.append(("LOW", "security.txt fayli yo'q (mas'ul aloqa uchun tavsiya)."))

    if not d.get("has_spf"):
        out.append(("MED", "SPF yozuvi yo'q - email spoofing xavfi."))
    if not d.get("has_dmarc"):
        out.append(("MED", "DMARC yozuvi yo'q - email spoofing xavfi."))

    if not out:
        out.append(("OK", "Jiddiy muammo topilmadi (passiv tekshiruv doirasida)."))
    return out


def generate_pdf(r: dict[str, Any], out_dir: str, active: dict | None = None) -> str:
    d, s, h = r["dns"], r["ssl"], r["http"]
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Sarlavha bloki
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, _latin(r["domain"]), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, _latin("Sana: " + time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Findings (xulosa)
    findings = build_findings(r)
    counts = {"HIGH": 0, "MED": 0, "LOW": 0}
    for sev, _ in findings:
        if sev in counts:
            counts[sev] += 1
    _h2(pdf, "Xulosa")
    _kv(pdf, "Yuqori xavf:", str(counts["HIGH"]), BAD if counts["HIGH"] else None)
    _kv(pdf, "O'rta xavf:", str(counts["MED"]), WARN if counts["MED"] else None)
    _kv(pdf, "Past xavf:", str(counts["LOW"]))

    # Topilmalar
    _h2(pdf, "Topilmalar va tavsiyalar")
    color_map = {"HIGH": BAD, "MED": WARN, "LOW": (90, 90, 90), "OK": OKC}
    marker_w = 18
    for sev, text in findings:
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*color_map[sev])
        pdf.cell(marker_w, 6, f"[{sev}]", new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 10)
        avail = pdf.w - pdf.r_margin - pdf.l_margin - marker_w
        pdf.multi_cell(avail, 6, _latin(text), new_x="LMARGIN", new_y="NEXT")

    # DNS
    _h2(pdf, "DNS")
    _kv(pdf, "A:", ", ".join(d.get("A", [])) or "-")
    if d.get("AAAA"):
        _kv(pdf, "AAAA:", ", ".join(d["AAAA"]))
    _kv(pdf, "MX:", str(len(d.get("MX", []))) + " ta")
    _kv(pdf, "NS:", ", ".join(d.get("NS", [])) or "-")
    _kv(pdf, "SPF:", "bor" if d.get("has_spf") else "yo'q")
    _kv(pdf, "DMARC:", "bor" if d.get("has_dmarc") else "yo'q")

    # SSL
    _h2(pdf, "SSL / TLS")
    if s.get("ok"):
        _kv(pdf, "Protokol:", str(s.get("protocol")))
        _kv(pdf, "Beruvchi:", str(s.get("issuer")))
        _kv(pdf, "Amal qiladi:", f"{s.get('days_left')} kun")
    else:
        _kv(pdf, "Holat:", "ulanib bo'lmadi", BAD)

    # HTTP
    _h2(pdf, "HTTP xavfsizlik header'lari")
    if h.get("ok"):
        _kv(pdf, "Status:", str(h.get("status")))
        if h.get("server"):
            _kv(pdf, "Server:", str(h.get("server")))
        _kv(pdf, "Mavjud:", ", ".join(h.get("present", [])) or "-", OKC)
        _kv(pdf, "Yo'q:", ", ".join(h.get("missing", [])) or "-", WARN if h.get("missing") else None)
    else:
        _kv(pdf, "Holat:", "javob yo'q", BAD)

    # Faol skan (agar bo'lsa)
    if active and active.get("authorized"):
        _h2(pdf, "Faol tekshiruv (portlar)")
        _kv(pdf, "IP:", str(active.get("ip", "-")))
        openp = active.get("open", [])
        _kv(pdf, "Ochiq portlar:", ", ".join(map(str, openp)) or "topilmadi",
            WARN if openp else OKC)

    # Izoh
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 5, _latin(
        "Ushbu hisobot avtomatik tekshiruv asosida tayyorlangan. Faol tekshiruv "
        "faqat tasdiqlangan yoki ruxsat berilgan nishonlarga o'tkaziladi."
    ))
    pdf.set_text_color(0, 0, 0)

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"report_{r['domain']}_{int(time.time())}.pdf")
    pdf.output(path)
    return path
