"""Skan natijasidan professional PDF hisobot yaratadi (fpdf2).

Eslatma: standart Helvetica shrifti latin-1 bilan cheklangan, shuning uchun
matnlar sodda lotin harflarida (o', g' kabi apostrof bilan) yoziladi va
emoji ishlatilmaydi. Bu hisobotni mijozga yuboriladigan toza hujjat qiladi.
"""
from __future__ import annotations

import os
import time
from typing import Any

from fpdf import FPDF

BRAND = "SentryScan Security Report"
ACCENT = (20, 90, 160)
GREY = (110, 110, 110)
OKC = (25, 135, 60)
WARN = (200, 120, 0)
BAD = (190, 40, 40)


def _latin(s: str) -> str:
    """latin-1 ga sig'maydigan belgilarni almashtiradi."""
    repl = {"’": "'", "‘": "'", "“": '"', "”": '"', "–": "-", "—": "-", "•": "-", "…": "..."}
    for a, b in repl.items():
        s = s.replace(a, b)
    return s.encode("latin-1", "replace").decode("latin-1")


class _PDF(FPDF):
    def header(self) -> None:
        self.set_fill_color(*ACCENT)
        self.rect(0, 0, self.w, 22, "F")
        self.set_xy(12, 6)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, BRAND)
        self.set_text_color(0, 0, 0)
        self.ln(20)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GREY)
        self.cell(0, 8, f"Generated by SentryScan  |  Page {self.page_no()}", align="C")
        self.set_text_color(0, 0, 0)


def _h2(pdf: _PDF, text: str) -> None:
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 8, _latin(text), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.set_draw_color(*ACCENT)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(2)


def _kv(pdf: _PDF, key: str, val: str, color=None) -> None:
    key_w = 45
    pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(key_w, 6, _latin(key), new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "", 10)
    if color:
        pdf.set_text_color(*color)
    avail = pdf.w - pdf.r_margin - pdf.l_margin - key_w
    pdf.multi_cell(avail, 6, _latin(val), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)


def build_findings(r: dict[str, Any]) -> list[tuple[str, str]]:
    """(daraja, matn) ro'yxati. daraja: OK/LOW/MED/HIGH."""
    out: list[tuple[str, str]] = []
    d, s, h = r["dns"], r["ssl"], r["http"]

    if s.get("ok"):
        dl = s.get("days_left")
        if dl is not None and dl < 0:
            out.append(("HIGH", "SSL sertifikat muddati tugagan!"))
        elif dl is not None and dl < 21:
            out.append(("MED", f"SSL sertifikat muddati tez tugaydi ({dl} kun)."))
    elif h.get("ok") and not h.get("https"):
        out.append(("HIGH", "Sayt faqat HTTP orqali ishlaydi - trafik shifrlanmagan. HTTPS o'rnating."))
    else:
        out.append(("MED", "HTTPS/SSL ulanib bo'lmadi yoki sozlanmagan."))

    if h.get("ok"):
        for miss in h.get("missing", []):
            sev = "MED" if miss in ("HSTS", "CSP") else "LOW"
            out.append((sev, f"Xavfsizlik header'i yo'q: {miss}."))
        if not h.get("security_txt"):
            out.append(("LOW", "security.txt fayli yo'q (mas'ul aloqa uchun tavsiya)."))

    if not d.get("has_spf"):
        out.append(("MED", "SPF yozuvi yo'q - email spoofing xavfi."))
    if not d.get("has_dmarc"):
        out.append(("MED", "DMARC yozuvi yo'q - email spoofing xavfi."))

    if not out:
        out.append(("OK", "Jiddiy muammo topilmadi (passiv tekshiruv doirasida)."))
    return out


SEV_COLOR = {"CRITICAL": (150, 20, 20), "HIGH": (190, 60, 20),
             "MEDIUM": (180, 130, 0), "LOW": (30, 100, 160), "INFO": (110, 110, 110)}


def generate_deep_pdf(r: dict[str, Any], out_dir: str) -> str:
    """Chuqur skan (auto-pentester) natijasidan PDF hisobot."""
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, _latin(r["domain"]), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, _latin("Chuqur skan (auto-pentester) — " +
             time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    c = r["counts"]
    score = r["score"]
    _h2(pdf, "Xulosa")
    sc_color = OKC if score >= 80 else (WARN if score >= 50 else BAD)
    _kv(pdf, "Xavfsizlik bali:", f"{score}/100", sc_color)
    _kv(pdf, "Kritik:", str(c.get("CRITICAL", 0)), BAD if c.get("CRITICAL") else None)
    _kv(pdf, "Yuqori:", str(c.get("HIGH", 0)), BAD if c.get("HIGH") else None)
    _kv(pdf, "O'rta:", str(c.get("MEDIUM", 0)), WARN if c.get("MEDIUM") else None)
    _kv(pdf, "Past:", str(c.get("LOW", 0)))
    if r.get("server"):
        _kv(pdf, "Server:", str(r["server"]))

    _h2(pdf, "Topilmalar")
    findings = r["findings"]
    if not findings:
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, _latin("Jiddiy muammo topilmadi."), new_x="LMARGIN", new_y="NEXT")
    for i, f in enumerate(findings, 1):
        col = SEV_COLOR.get(f["sev"], (0, 0, 0))
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*col)
        pdf.cell(24, 6, f"[{f['sev'][:4]}]", new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(0, 0, 0)
        avail = pdf.w - pdf.r_margin - pdf.l_margin - 24
        pdf.multi_cell(avail, 6, _latin(f"{i}. {f['title']}"), new_x="LMARGIN", new_y="NEXT")
        if f.get("detail"):
            pdf.set_x(pdf.l_margin + 24)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*GREY)
            pdf.multi_cell(avail, 5, _latin(f["detail"]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
        if f.get("fix"):
            pdf.set_x(pdf.l_margin + 24)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*ACCENT)
            pdf.multi_cell(avail, 5, _latin("Tuzatish: " + f["fix"]), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 5, _latin(
        "Avtomatik zararsiz skan (faqat o'qish so'rovlari). Faol ekspluatatsiya "
        "va qo'lda tekshiruv alohida xizmat. Faqat ruxsat berilgan nishonlar uchun."
    ))
    pdf.set_text_color(0, 0, 0)

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"deepscan_{r['domain']}_{int(time.time())}.pdf")
    pdf.output(path)
    return path


def generate_recon_pdf(r: dict[str, Any], out_dir: str) -> str:
    """Recon (subdomen + texnologiya) natijasidan PDF hisobot."""
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, _latin(r["domain"]), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, _latin("Recon (passiv OSINT) - " +
             time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    t = r.get("tech", {})
    _h2(pdf, "Texnologiyalar")
    if t.get("ok"):
        _kv(pdf, "Server:", str(t.get("server") or "-"))
        _kv(pdf, "X-Powered-By:", str(t.get("powered_by") or "-"))
        _kv(pdf, "Aniqlangan:", ", ".join(t.get("tech", [])) or "-")
    else:
        _kv(pdf, "Holat:", "javob yo'q", BAD)

    subs = r.get("subdomains", [])
    ips = r.get("ips", {})
    _h2(pdf, f"Subdomenlar ({len(subs)})")
    if not subs:
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, _latin("Certificate Transparency (crt.sh) da topilmadi."),
                       new_x="LMARGIN", new_y="NEXT")
    for host in subs:
        ip = ips.get(host)
        _kv(pdf, host + ":", str(ip or "(hal qilinmadi)"))

    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 5, _latin(
        "Subdomenlar Certificate Transparency (crt.sh) ochiq jurnalidan olingan - "
        "nishonga hech qanday so'rov yuborilmagan. Texnologiya HTTP javobidan aniqlangan. "
        "Faqat ruxsat berilgan nishonlar uchun."
    ))
    pdf.set_text_color(0, 0, 0)

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"recon_{r['domain']}_{int(time.time())}.pdf")
    pdf.output(path)
    return path


def generate_nuclei_pdf(r: dict[str, Any], out_dir: str) -> str:
    """Nuclei skan natijasidan PDF hisobot."""
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    target = r.get("target", "-")
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _latin(target), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, _latin("Nuclei skan - " +
             time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    findings = r.get("findings", [])
    counts: dict[str, int] = {}
    for f in findings:
        counts[f["sev"]] = counts.get(f["sev"], 0) + 1
    _h2(pdf, "Xulosa")
    _kv(pdf, "Jami topilma:", str(len(findings)), BAD if findings else OKC)
    _kv(pdf, "Kritik:", str(counts.get("CRITICAL", 0)), BAD if counts.get("CRITICAL") else None)
    _kv(pdf, "Yuqori:", str(counts.get("HIGH", 0)), BAD if counts.get("HIGH") else None)
    _kv(pdf, "O'rta:", str(counts.get("MEDIUM", 0)), WARN if counts.get("MEDIUM") else None)

    _h2(pdf, "Topilmalar")
    if not findings:
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, _latin("Nuclei tanlangan darajalarda muammo topmadi."),
                       new_x="LMARGIN", new_y="NEXT")
    for i, f in enumerate(findings, 1):
        col = SEV_COLOR.get(f["sev"], (0, 0, 0))
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*col)
        pdf.cell(24, 6, f"[{f['sev'][:4]}]", new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(0, 0, 0)
        avail = pdf.w - pdf.r_margin - pdf.l_margin - 24
        pdf.multi_cell(avail, 6, _latin(f"{i}. {f['title']}"), new_x="LMARGIN", new_y="NEXT")
        detail = f.get("detail") or ""
        if f.get("template"):
            detail = (detail + f"  [{f['template']}]").strip()
        if detail:
            pdf.set_x(pdf.l_margin + 24)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(*GREY)
            pdf.multi_cell(avail, 5, _latin(detail), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 5, _latin(
        "Nuclei (ProjectDiscovery) ochiq shablonlar asosidagi faol skan. Faqat "
        "tasdiqlangan yoki ruxsat berilgan nishonlar uchun o'tkaziladi."
    ))
    pdf.set_text_color(0, 0, 0)

    os.makedirs(out_dir, exist_ok=True)
    safe = "".join(ch if ch.isalnum() else "_" for ch in target)[:40]
    path = os.path.join(out_dir, f"nuclei_{safe}_{int(time.time())}.pdf")
    pdf.output(path)
    return path


def generate_pdf(r: dict[str, Any], out_dir: str, active: dict | None = None) -> str:
    d, s, h = r["dns"], r["ssl"], r["http"]
    pdf = _PDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Sarlavha bloki
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, _latin(r["domain"]), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, _latin("Sana: " + time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)

    # Findings (xulosa)
    findings = build_findings(r)
    counts = {"HIGH": 0, "MED": 0, "LOW": 0}
    for sev, _ in findings:
        if sev in counts:
            counts[sev] += 1
    _h2(pdf, "Xulosa")
    _kv(pdf, "Yuqori xavf:", str(counts["HIGH"]), BAD if counts["HIGH"] else None)
    _kv(pdf, "O'rta xavf:", str(counts["MED"]), WARN if counts["MED"] else None)
    _kv(pdf, "Past xavf:", str(counts["LOW"]))

    # Topilmalar
    _h2(pdf, "Topilmalar va tavsiyalar")
    color_map = {"HIGH": BAD, "MED": WARN, "LOW": (90, 90, 90), "OK": OKC}
    marker_w = 18
    for sev, text in findings:
        pdf.set_x(pdf.l_margin)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*color_map[sev])
        pdf.cell(marker_w, 6, f"[{sev}]", new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 10)
        avail = pdf.w - pdf.r_margin - pdf.l_margin - marker_w
        pdf.multi_cell(avail, 6, _latin(text), new_x="LMARGIN", new_y="NEXT")

    # DNS
    _h2(pdf, "DNS")
    _kv(pdf, "A:", ", ".join(d.get("A", [])) or "-")
    if d.get("AAAA"):
        _kv(pdf, "AAAA:", ", ".join(d["AAAA"]))
    _kv(pdf, "MX:", str(len(d.get("MX", []))) + " ta")
    _kv(pdf, "NS:", ", ".join(d.get("NS", [])) or "-")
    _kv(pdf, "SPF:", "bor" if d.get("has_spf") else "yo'q")
    _kv(pdf, "DMARC:", "bor" if d.get("has_dmarc") else "yo'q")

    # SSL
    _h2(pdf, "SSL / TLS")
    if s.get("ok"):
        _kv(pdf, "Protokol:", str(s.get("protocol")))
        _kv(pdf, "Beruvchi:", str(s.get("issuer")))
        _kv(pdf, "Amal qiladi:", f"{s.get('days_left')} kun")
    else:
        _kv(pdf, "Holat:", "ulanib bo'lmadi", BAD)

    # HTTP
    _h2(pdf, "HTTP xavfsizlik header'lari")
    if h.get("ok"):
        _kv(pdf, "Status:", str(h.get("status")))
        if h.get("server"):
            _kv(pdf, "Server:", str(h.get("server")))
        _kv(pdf, "Mavjud:", ", ".join(h.get("present", [])) or "-", OKC)
        _kv(pdf, "Yo'q:", ", ".join(h.get("missing", [])) or "-", WARN if h.get("missing") else None)
    else:
        _kv(pdf, "Holat:", "javob yo'q", BAD)

    # Faol skan (agar bo'lsa)
    if active and active.get("authorized"):
        _h2(pdf, "Faol tekshiruv (portlar)")
        _kv(pdf, "IP:", str(active.get("ip", "-")))
        openp = active.get("open", [])
        _kv(pdf, "Ochiq portlar:", ", ".join(map(str, openp)) or "topilmadi",
            WARN if openp else OKC)

    # Izoh
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 5, _latin(
        "Ushbu hisobot avtomatik tekshiruv asosida tayyorlangan. Faol tekshiruv "
        "faqat tasdiqlangan yoki ruxsat berilgan nishonlarga o'tkaziladi."
    ))
    pdf.set_text_color(0, 0, 0)

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"report_{r['domain']}_{int(time.time())}.pdf")
    pdf.output(path)
    return path
